
class InitData:
    sp_type = {
        1: '自动回复',
        2: '攻击回复',
        4: '受击回复',
        8: '被动'
    }
    class_type = {
        1: '先锋',
        2: '近卫',
        3: '重装',
        4: '狙击',
        5: '术师',
        6: '辅助',
        7: '医疗',
        8: '特种'
    }
    skill_type = {
        0: '被动',
        1: '手动触发',
        2: '自动触发'
    }
    skill_level = {
        1: '等级1',
        2: '等级2',
        3: '等级3',
        4: '等级4',
        5: '等级5',
        6: '等级6',
        7: '等级7',
        8: '专精1',
        9: '专精2',
        10: '专精3'
    }
    potential_rank = {
        1: '一',
        2: '丅',
        3: '上',
        4: '止',
        5: '正'
    }
    voices = [
        "任命助理", "任命队长", "编入队伍", "问候", "闲置",
        "交谈1", "交谈2", "交谈3", "晋升后交谈1", "晋升后交谈2",
        "信赖提升后交谈1", "信赖提升后交谈2", "信赖提升后交谈3",
        "精英化晋升1", "精英化晋升2",
        "行动出发", "行动失败", "行动开始", "3星结束行动", "4星结束行动", "非3星结束行动",
        "选中干员1", "选中干员2", "部署1", "部署2", "作战中1", "作战中2", "作战中3", "作战中4",
        "戳一下", "信赖触摸", "干员报到", "进驻设施", "观看作战记录", "标题"
    ]
    operator_pool_list = [
        {"pool_name": "常驻寻访", "pickup_6": "塞雷娅,嵯峨", "pickup_5": "食铁兽,灰喉,四月", "pickup_4": "", "pickup_s": "",
         "limit_pool": 0},
        {"pool_name": "联合行动", "pickup_6": "棘刺,夜莺,铃兰,温蒂", "pickup_5": "临光,安哲拉,赫默,芙兰卡,极境,莱恩哈特", "pickup_4": "",
         "pickup_s": None,
         "limit_pool": 2},
        {"pool_name": "银灰色的荣耀", "pickup_6": "银灰", "pickup_5": "初雪,崖心", "pickup_4": "角峰",
         "pickup_s": None,
         "limit_pool": 0},
        {"pool_name": "搅动潮汐之剑", "pickup_6": "斯卡蒂", "pickup_5": "夜魔,临光", "pickup_4": "猎蜂,暗索",
         "pickup_s": None,
         "limit_pool": 0},
        {"pool_name": "鞘中赤红", "pickup_6": "陈", "pickup_5": "诗怀雅,食铁兽", "pickup_4": "格雷伊",
         "pickup_s": None,
         "limit_pool": 0},
        {"pool_name": "龙门特别行动专员寻访", "pickup_6": "星熊", "pickup_5": "雷蛇,陨星", "pickup_4": "",
         "pickup_s": None,
         "limit_pool": 0},
        {"pool_name": "深夏的守夜人", "pickup_6": "黑", "pickup_5": "格劳克斯,蓝毒", "pickup_4": "苏苏洛",
         "pickup_s": None,
         "limit_pool": 0},
        {"pool_name": "久铸尘铁", "pickup_6": "赫拉格", "pickup_5": "星极,可颂", "pickup_4": "桃金娘",
         "pickup_s": None,
         "limit_pool": 0},
        {"pool_name": "火舞之人", "pickup_6": "艾雅法拉", "pickup_5": "普罗旺斯,幽灵鲨", "pickup_4": "",
         "pickup_s": None,
         "limit_pool": 0},
        {"pool_name": "冰封原野", "pickup_6": "麦哲伦", "pickup_5": "送葬人,赫默", "pickup_4": "红云",
         "pickup_s": None,
         "limit_pool": 0},
        {"pool_name": "锁与匙的守卫者", "pickup_6": "莫斯提马", "pickup_5": "槐琥,守林人", "pickup_4": "梅",
         "pickup_s": None,
         "limit_pool": 0},
        {"pool_name": "凝电之钻", "pickup_6": "能天使", "pickup_5": "布洛卡,苇草", "pickup_4": "",
         "pickup_s": None,
         "limit_pool": 0},
        {"pool_name": "热情，膨胀，爆发", "pickup_6": "煌", "pickup_5": "灰喉,天火", "pickup_4": "安比尔",
         "pickup_s": None,
         "limit_pool": 0},
        {"pool_name": "地生五金", "pickup_6": "年,阿", "pickup_5": "吽", "pickup_4": "",
         "pickup_s": None,
         "limit_pool": 1},
        {"pool_name": "百种兵器", "pickup_6": "刻俄柏", "pickup_5": "拉普兰德,惊蛰", "pickup_4": "",
         "pickup_s": None,
         "limit_pool": 0},
        {"pool_name": "草垛上的风笛声", "pickup_6": "风笛", "pickup_5": "慑砂,凛冬", "pickup_4": "宴",
         "pickup_s": None,
         "limit_pool": 0},
        {"pool_name": "往日幻象", "pickup_6": "傀影", "pickup_5": "巫恋,白面鸮", "pickup_4": "刻刀",
         "pickup_s": None,
         "limit_pool": 0},
        {"pool_name": "遗愿焰火", "pickup_6": "W,温蒂", "pickup_5": "极境", "pickup_4": "",
         "pickup_s": None,
         "limit_pool": 1},
        {"pool_name": "雾漫荒林", "pickup_6": "", "pickup_5": "石棉,月禾", "pickup_4": "",
         "pickup_s": None,
         "limit_pool": 0},
        {"pool_name": "雪落晨心", "pickup_6": "早露", "pickup_5": "莱恩哈特,真理", "pickup_4": "波登可",
         "pickup_s": None,
         "limit_pool": 0},
        {"pool_name": "君影轻灵", "pickup_6": "铃兰", "pickup_5": "断崖,夜魔", "pickup_4": "卡达",
         "pickup_s": None,
         "limit_pool": 0},
        {"pool_name": "流沙涡旋", "pickup_6": "", "pickup_5": "蜜蜡,贾维", "pickup_4": "",
         "pickup_s": None,
         "limit_pool": 0},
        {"pool_name": "不羁逆流", "pickup_6": "棘刺", "pickup_5": "安哲拉,普罗旺斯", "pickup_4": "孑",
         "pickup_s": None,
         "limit_pool": 0},
        {"pool_name": "燃钢之心，暴躁铁皮", "pickup_6": "森蚺", "pickup_5": "燧石,陨星", "pickup_4": "酸糖",
         "pickup_s": None,
         "limit_pool": 0},
        {"pool_name": "无拘熔火", "pickup_6": "史尔特尔", "pickup_5": "四月,极境", "pickup_4": "芳汀",
         "pickup_s": None,
         "limit_pool": 0},
        {"pool_name": "瑕光微明", "pickup_6": "瑕光", "pickup_5": "奥斯塔,白金", "pickup_4": "泡泡",
         "pickup_s": None,
         "limit_pool": 0},
        {"pool_name": "勿忘我", "pickup_6": "迷迭香,泥岩", "pickup_5": "絮雨", "pickup_4": "杰克",
         "pickup_s": None,
         "limit_pool": 1},
        {"pool_name": "自由的囚徒", "pickup_6": "山", "pickup_5": "卡夫卡,赫默", "pickup_4": "松果",
         "pickup_s": None,
         "limit_pool": 0},
        {"pool_name": "麦穗与赞美诗", "pickup_6": "空弦", "pickup_5": "爱丽丝,贾维", "pickup_4": "豆苗",
         "pickup_s": None,
         "limit_pool": 0},
        {"pool_name": "月隐晦明", "pickup_6": "夕,嵯峨", "pickup_5": "乌有", "pickup_4": "",
         "pickup_s": "年|5",
         "limit_pool": 0},
        {"pool_name": "进攻、防守、战术交汇", "pickup_6": "灰烬", "pickup_5": "霜华,闪击", "pickup_4": "",
         "pickup_s": None,
         "limit_pool": 1},
        {"pool_name": "沙海过客", "pickup_6": "异客", "pickup_5": "熔泉", "pickup_4": "",
         "pickup_s": None,
         "limit_pool": 0},
        {"pool_name": "深悼", "pickup_6": "浊心斯卡蒂,凯尔希", "pickup_5": "赤冬", "pickup_4": "",
         "pickup_s": 'W|5',
         "limit_pool": 1},
        {"pool_name": "革新交响曲", "pickup_6": "卡涅利安", "pickup_5": "绮良,崖心", "pickup_4": "深靛",
         "pickup_s": None,
         "limit_pool": 0},
        {"pool_name": "从星火中来", "pickup_6": "帕拉斯", "pickup_5": "幽灵鲨,红", "pickup_4": "",
         "pickup_s": None,
         "limit_pool": 0},
        {"pool_name": "盛夏新星", "pickup_6": "假日威龙陈,水月", "pickup_5": "羽毛笔", "pickup_4": "",
         "pickup_s": None,
         "limit_pool": 1},
    ]
    operator_gacha_config_list = [
        {"operator_name": "年", "operator_type": 0},
        {"operator_name": "W", "operator_type": 0},
        {"operator_name": "迷迭香", "operator_type": 0},
        {"operator_name": "夕", "operator_type": 0},
        {"operator_name": "浊心斯卡蒂", "operator_type": 0},
        {"operator_name": "假日威龙陈", "operator_type": 0},
        {"operator_name": "灰烬", "operator_type": 1},
        {"operator_name": "霜华", "operator_type": 1},
        {"operator_name": "闪击", "operator_type": 1},
        {"operator_name": "阿米娅", "operator_type": 2},
        {"operator_name": "阿米娅近卫", "operator_type": 2},
        {"operator_name": "暴行", "operator_type": 2},
        {"operator_name": "断罪者", "operator_type": 2},
        {"operator_name": "嘉维尔", "operator_type": 3},
        {"operator_name": "讯使", "operator_type": 3},
        {"operator_name": "微风", "operator_type": 3},
        {"operator_name": "伊桑", "operator_type": 3},
        {"operator_name": "坚雷", "operator_type": 3},
        {"operator_name": "清流", "operator_type": 4},
        {"operator_name": "因陀罗", "operator_type": 4},
        {"operator_name": "火神", "operator_type": 4},
        {"operator_name": "艾丝黛尔", "operator_type": 4},
        {"operator_name": "格拉尼", "operator_type": 5},
        {"operator_name": "锡兰", "operator_type": 5},
        {"operator_name": "炎客", "operator_type": 5},
        {"operator_name": "拜松", "operator_type": 5},
        {"operator_name": "雪雉", "operator_type": 5},
        {"operator_name": "铸铁", "operator_type": 5},
        {"operator_name": "苦艾", "operator_type": 5},
        {"operator_name": "亚叶", "operator_type": 5},
        {"operator_name": "特米米", "operator_type": 5},
        {"operator_name": "薄绿", "operator_type": 5},
        {"operator_name": "鞭刃", "operator_type": 5},
        {"operator_name": "罗宾", "operator_type": 5},
        {"operator_name": "炎狱炎熔", "operator_type": 5},
        {"operator_name": "暴雨", "operator_type": 5},
        {"operator_name": "歌蕾蒂娅", "operator_type": 5},
        {"operator_name": "战车", "operator_type": 6},
        {"operator_name": "柏喙", "operator_type": 7},
        {"operator_name": "稀音", "operator_type": 7},
        {"operator_name": "图耶", "operator_type": 7},
        {"operator_name": "预备干员-近战", "operator_type": 8},
        {"operator_name": "预备干员-狙击", "operator_type": 8},
        {"operator_name": "预备干员-后勤", "operator_type": 8},
        {"operator_name": "预备干员-术师", "operator_type": 8},
        {"operator_name": "Sharp", "operator_type": 8},
        {"operator_name": "Stormeye", "operator_type": 8},
        {"operator_name": "Pith", "operator_type": 8},
        {"operator_name": "Touch", "operator_type": 8},
    ]
